### PR TITLE
ci: work around Cargo breakage by setting RUST_TARGET_PATH

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0fd35a4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0fd35a4ea2a47cb1a8274e49e7646e5b18b1ea5b with merge 1429bb04d55117410d11c7388fe3cca32bd73577...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/nvptx/builds/323194965?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 1429bb04d55117410d11c7388fe3cca32bd73577 to master...

**Pull request merged**
