### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a807615 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a807615 with merge a807615...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/nvptx/builds/233895735?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6adc37b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6adc37b with merge 6adc37b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/nvptx/builds/233896138?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 6adc37b87cb5255a7c56a7b258db8aafb05c4754 to master...

**Pull request merged**
