### PR TITLE
change random sample code to be more intuitive

### PR DESCRIPTION
**Pull request by vadixidav**
This PR has basically no purpose other than to use more intuitive coding style in those three lines. All I can say: it bothered me.

### CODE REVIEW

**Comment by japaric** [comment]
Thanks!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a980e02 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a980e02 with merge a980e02...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/nvptx/builds/234343916?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing a980e0264daabe76196c6f34c863f616aa3c1281 to master...

**Pull request merged**
