### PR TITLE
Typo fix on README.md

### PR DESCRIPTION
**Pull request by antoinewdg**
It's in the title :)

### CODE REVIEW

**Comment by japaric** [comment]
Thanks!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9fed676 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9fed676 with merge 9fed676...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/nvptx/builds/234006369?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 9fed67607ed015a2bf9b44b34cf89a9b355f6f14 to master...

**Pull request merged**
